from abc import ABC, abstractmethod
from uuid import UUID
from .models import Risk
class RiskRepository(ABC):
    @abstractmethod
    def get_by_id(self,risk_id:UUID)->Risk|None:...
    @abstractmethod
    def list_by_project(self,project_id:UUID)->list[Risk]:...
    @abstractmethod
    def list_by_decision(self,decision_id:UUID)->list[Risk]:...
    @abstractmethod
    def exists_by_title(self,project_id:UUID,title:str)->bool:...
    @abstractmethod
    def save(self,risk:Risk)->Risk:...
