from abc import ABC, abstractmethod
from uuid import UUID
from .models import User
class UserRepository(ABC):
    @abstractmethod
    def get_by_id(self,user_id:UUID)->User|None: ...
    @abstractmethod
    def get_by_email(self,email:str)->User|None: ...
    @abstractmethod
    def exists_by_email(self,email:str)->bool: ...
    @abstractmethod
    def save(self,user:User)->User: ...
