from abc import ABC, abstractmethod
from uuid import UUID
from .models import Decision
class DecisionRepository(ABC):
    @abstractmethod
    def get_by_id(self,decision_id:UUID)->Decision|None: ...
    @abstractmethod
    def list_by_project(self,project_id:UUID)->list[Decision]: ...
    @abstractmethod
    def list_by_organization(self,organization_id:UUID)->list[Decision]: ...
    @abstractmethod
    def exists_by_title(self,project_id:UUID,title:str)->bool: ...
    @abstractmethod
    def save(self,decision:Decision)->Decision: ...
