from abc import ABC, abstractmethod
from uuid import UUID
from .models import Option
class OptionRepository(ABC):
    @abstractmethod
    def get_by_id(self,option_id:UUID)->Option|None: ...
    @abstractmethod
    def list_by_decision(self,decision_id:UUID)->list[Option]: ...
    @abstractmethod
    def exists_by_title(self,decision_id:UUID,title:str)->bool: ...
    @abstractmethod
    def save(self,option:Option)->Option: ...
