from abc import ABC, abstractmethod
from uuid import UUID
from .models import Scenario
class ScenarioRepository(ABC):
    @abstractmethod
    def get_by_id(self,scenario_id:UUID)->Scenario|None: ...
    @abstractmethod
    def list_by_decision(self,decision_id:UUID)->list[Scenario]: ...
    @abstractmethod
    def list_by_option(self,option_id:UUID)->list[Scenario]: ...
    @abstractmethod
    def exists_by_name(self,decision_id:UUID,name:str)->bool: ...
    @abstractmethod
    def save(self,scenario:Scenario)->Scenario: ...
