from typing import Protocol
from .commands import *
class UserLifecycleHandler(Protocol):
    def create(self, command:CreateUser): ...
    def suspend(self, command:SuspendUser): ...
    def reactivate(self, command:ReactivateUser): ...
    def archive(self, command:ArchiveUser): ...
    def rename(self, command:RenameUser): ...
