from abc import ABC, abstractmethod
from uuid import UUID
class ExecutionRepository(ABC):
 @abstractmethod
 def get_by_id(self,execution_id:UUID): ...
 @abstractmethod
 def list_by_project(self,project_id:UUID): ...
 @abstractmethod
 def exists_by_title(self,project_id:UUID,title:str,exclude_id:UUID|None=None): ...
 @abstractmethod
 def save(self,execution): ...
